services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-crm-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - mini-crm-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: mini-crm-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mini-crm-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mini-crm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mini_crm
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mini_crm
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mini-crm-network
    ports:
      - "3306:3306"

networks:
  mini-crm-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
